### PR TITLE
Add message to user in getlog and getoutput in case no files to retrieve.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**

### CODE REVIEW

**Comment by AndresTanasijczuk** [comment]
This pull request should go together with https://github.com/dmwm/CRABServer/pull/4625

**Comment by AndresTanasijczuk** [comment]
Changed the commit. Now the server doesn't pass any message and the client just gets an empty list if the transfer flag was False. The client gives a generic message asking the user if he set the transfer flag to True at submission time.

Tests in my private VM:

$ crab getoutput -d crab_check_transferFiles_toF_tlF_1
WARNING: Incompatible CRABClient version "development" 
Server is saying that compatible versions are: ['3.3.8', '3.3.9.rc2', '3.3.9', '3.3.10', '3.3.9.pre2']
No files to retrieve.
Did you set the General.transferOutputs parameter to True in the CRAB configuration file when you submitted the task? If General.transferOutputs was set to False (default is True), the output files were not staged out from the worker node and can not be retrieved.
Log file is /afs/cern.ch/work/a/atanasi/CRAB3-tutorial/CMSSW_7_0_5/src/crab_check_transferFiles_toF_tlF_1/crab.log

$ crab getlog -d crab_check_transferFiles_toF_tlF_1
WARNING: Incompatible CRABClient version "development" 
Server is saying that compatible versions are: ['3.3.8', '3.3.9.rc2', '3.3.9', '3.3.10', '3.3.9.pre2']
No files to retrieve.
Did you set the General.transferLogs parameter to True in the CRAB configuration file when you submitted the task? If General.transferLogs was not set to True (default is False), the log files were not staged out from the worker node and can not be retrieved.
Log file is /afs/cern.ch/work/a/atanasi/CRAB3-tutorial/CMSSW_7_0_5/src/crab_check_transferFiles_toF_tlF_1/crab.log

**Comment by AndresTanasijczuk** [comment]
Changed the message to users as suggested by @belforte in https://github.com/dmwm/CRABServer/pull/4625

**Comment by belforte** [comment]
I am surely confused a lot.. but why getlog and getoutput use different message  ?
one has "unless General.transferLogs=True", the other "if General.transferOutputs=False"
are there different default values ?

Also, shouldn't the message say also "No file retrieved" ?

**Comment by AndresTanasijczuk** [comment]
Because the default values are different: General.transferLogs defaults to False, while General.transferOutputs defaults to True. Do you prefer the same message for getoutput as for getlog?
"No files retrieved." is already printed by getcommand.py in https://github.com/AndresTanasijczuk/CRABClient/commit/429f3556252ded1f50d2c90aa24d078ea77dd03e#diff-1259e30c4a45cc5db4edceac9c55d399R88 when called from here https://github.com/AndresTanasijczuk/CRABClient/commit/429f3556252ded1f50d2c90aa24d078ea77dd03e#diff-a1191c2ee429bed3aa2a9d39707c2d24R16 and here https://github.com/AndresTanasijczuk/CRABClient/commit/429f3556252ded1f50d2c90aa24d078ea77dd03e#diff-ab72a7e543804ee99fa136076bd00f32R19

**Comment by belforte** [comment]
I see, thanks. All OK.

**Pull request merged**
