### PR TITLE
Add --force option in resubmit command.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
I will make the corresponding pull request for the server once https://github.com/dmwm/CRABServer/pull/4773 is merged. So don't merge this pull if you don't plan to merge https://github.com/dmwm/CRABServer/pull/4773

### CODE REVIEW

**Comment by AndresTanasijczuk** [comment]
Ok, dmwm/CRABServer#4773 was merged and I made the corresponding pull in the server for the --force option: https://github.com/dmwm/CRABServer/pull/4781

**Comment by mmascher** [comment]
Needs a rebase

**Comment by mmascher** [comment]
It needs a rebase

**Comment by AndresTanasijczuk** [comment]
rebased

**Pull request merged**
