### PR TITLE
checkwrite - adapt to rucio 1.29 api

### PR DESCRIPTION
**Pull request by mapellidario**
This was requested in https://github.com/dmwm/CRABServer/issues/7364#issuecomment-1219350157

### description

Without this PR, `crab checkwrite` fails with

```plaintext
> crab checkwrite --checksum=yes --site=T2_IT_Pisa
Will check write permission in the default location /store/user/<username>
Validating LFN /store/user/dmapelli...
LFN /store/user/dmapelli is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/dmapelli on site T2_IT_Pisa
Will use PFN: Failed to resolve LNF to PFN via Rucio. Error is:
 RSE does not support requested operation.
Details: Operation third_party_copy is not supported
srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_085201/crab3checkwrite_20220819_085201.tmp
```

This is caused by the rucio upgrade to v1.29.

With this PR, `checkwrite` works again as expected [1].

### more info

<details><summary>[1]</summary>

```plaintext
> crab checkwrite --checksum=yes --site=T2_IT_Pisa
Will check write permission in the default location /store/user/<username>
Validating LFN /store/user/dmapelli...
LFN /store/user/dmapelli is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/dmapelli on site T2_IT_Pisa
Will use PFN: davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/crab3checkwrite_20220819_095238.tmp

Attempting to create (dummy) directory crab3checkwrite_20220819_095238 and copy (dummy) file crab3checkwrite_20220819_095238.tmp to /store/user/dmapelli

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 -K ADLER32 file:///afs/cern.ch/user/d/dmapelli/crab/client/crab3checkwrite_20220819_095238.tmp 'davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/crab3checkwrite_20220819_095238.tmp'
Please wait...

Successfully created directory crab3checkwrite_20220819_095238 and copied file crab3checkwrite_20220819_095238.tmp to /store/user/dmapelli

Attempting to delete file davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/crab3checkwrite_20220819_095238.tmp

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/crab3checkwrite_20220819_095238.tmp'
Please wait...

Successfully deleted file davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/crab3checkwrite_20220819_095238.tmp

Attempting to delete directory davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/'
Please wait...

Successfully deleted directory davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_095238/

Checkwrite Result:
Success: Able to write in /store/user/dmapelli on site T2_IT_Pisa
```
</details>

### CODE REVIEW

**Comment by mapellidario** [comment]
Despite what would seem reasonable at first sight, using ` for operation in ['write', 'read']:` make `checkwrite` fail with (full log at [1])

```plaintext
Attempting to delete directory srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/
Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/'
Please wait...
Failed running delete command
  Stdout:
    srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/  MISSING
Failed to delete directory srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/
```

However if I set ` for operation in ['third_party_copy_write', 'write', 'read']:`, then everything works file, [2].

If I have to guess, when we use `gfal-rm srm://path/dir/file1` and `dir` contains only `file1`, then also `dir` is removed and the last command  `gfal-rm srm://path/dir/` fails because it can not find the directory. However I have not checked this assumption yet.

Somehow, this is not the case for `gfal-rm davs://path/dir/file1`

<details><summary>[1]</summary>

```plaintext
> crab checkwrite --checksum=yes --site=T2_IT_Pisa
Will check write permission in the default location /store/user/<username>
Validating LFN /store/user/dmapelli...
LFN /store/user/dmapelli is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/dmapelli on site T2_IT_Pisa
Will use PFN: srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/crab3checkwrite_20220819_192943.tmp

Attempting to create (dummy) directory crab3checkwrite_20220819_192943 and copy (dummy) file crab3checkwrite_20220819_192943.tmp to /store/user/dmapelli

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 -K ADLER32 file:///afs/cern.ch/user/d/dmapelli/crab/client/CRABClient/crab3checkwrite_20220819_192943.tmp 'srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/crab3checkwrite_20220819_192943.tmp'
Please wait...

Successfully created directory crab3checkwrite_20220819_192943 and copied file crab3checkwrite_20220819_192943.tmp to /store/user/dmapelli

Attempting to delete file srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/crab3checkwrite_20220819_192943.tmp

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/crab3checkwrite_20220819_192943.tmp'
Please wait...

Successfully deleted file srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/crab3checkwrite_20220819_192943.tmp

Attempting to delete directory srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/'
Please wait...
Failed running delete command
  Stdout:
    srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/  MISSING


Failed to delete directory srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_192943/

Checkwrite Result:
Error: CRAB3 is able to copy but unable to delete directory in /store/user/dmapelli on site T2_IT_Pisa. Asynchronous Stage Out with CRAB3 will fail.
       You may want to contact the site administrators sending them the 'crab checkwrite' output as printed above.
Note: You cannot write to a site if you did not ask permission.
```

</details>

<details><summary>[2]</summary>

```plaintext
> crab checkwrite --checksum=yes --site=T2_IT_Pisa
Will check write permission in the default location /store/user/<username>
Validating LFN /store/user/dmapelli...
LFN /store/user/dmapelli is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/dmapelli on site T2_IT_Pisa
Will use PFN: davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/crab3checkwrite_20220819_193401.tmp

Attempting to create (dummy) directory crab3checkwrite_20220819_193401 and copy (dummy) file crab3checkwrite_20220819_193401.tmp to /store/user/dmapelli

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 -K ADLER32 file:///afs/cern.ch/user/d/dmapelli/crab/client/CRABClient/crab3checkwrite_20220819_193401.tmp 'davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/crab3checkwrite_20220819_193401.tmp'
Please wait...

Successfully created directory crab3checkwrite_20220819_193401 and copied file crab3checkwrite_20220819_193401.tmp to /store/user/dmapelli

Attempting to delete file davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/crab3checkwrite_20220819_193401.tmp

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/crab3checkwrite_20220819_193401.tmp'
Please wait...

Successfully deleted file davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/crab3checkwrite_20220819_193401.tmp

Attempting to delete directory davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/'
Please wait...

Successfully deleted directory davs://stwebdav.pi.infn.it:8443/cms/store/user/dmapelli/crab3checkwrite_20220819_193401/

Checkwrite Result:
Success: Able to write in /store/user/dmapelli on site T2_IT_Pisa
```
</details>

**Comment by belforte** [comment]
> If I have to guess, when we use gfal-rm srm://path/dir/file1 and dir contains only file1, then also dir is removed 

that'd be sort of a viloation of all that's sacred. I suspect a problem with Pisa RSE config. Can you try the same at other sites ?

**Comment by mapellidario** [comment]
On `T2_CH_CERN` it works indeed. In this case `rucio` selected the `gsiftp://` protocol, while for Pisa it selected `srm://`, but I do not know if this can make a difference.

**Comment by mapellidario** [comment]
Given your suggestion at https://github.com/dmwm/CRABServer/issues/7364#issuecomment-1221086179 , we can stick with the latest commit, which uses `third_party_copy_write`, so that we effectively always select `davs://` and live happily with it.

 I would not worry too much about that problem with `srm://` at Pisa. 
 
 thanks!

**Pull request merged**
