### PR TITLE
Revert Use clean env for proxy delegation #4594

### PR DESCRIPTION
**Pull request by juztas**
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1421.html

### CODE REVIEW

**Comment by jpata** [comment]
version 3.3.1602 worked for submission
`160310_170953:jpata_crab_tth_VHBBHeppyV21pre_tthbbV4pre_nome_ttHTobb_M125_13TeV_powheg_Py8__fall15MAv2-pu25ns15v1_72as_v12-v1`

**Comment by juztas** [comment]
@mmascher @emaszs can you merge this, create new tag, create pull request to cmsdist and merge?

**Comment by mmascher** [comment]
Tag created, I'd leave for emilis to create a pull request for the client on cmsdist. Also, maybe we should add Emilis to the list of people allowed to create tags and merge branch on CRAB3. Comments  @ericvaandering  @belforte ?

**Comment by belforte** [comment]
yes, we should add Emilis. I think Eric is the only one who can do that.

**Pull request merged**
