### PR TITLE
add parasitic upload of tarablls to S3. Fix #4996

### LINKED ISSUE #4996: add parasitic tarballs upload to S3 cache
so that we can check how ti works from "all places and all sandboxes".
Need a way to record things. Currently looking at https://cmsmonit-docs.web.cern.ch/NATS/nats/
A fall back will be an ad-hoc small, named file to current crabcache, a bit like done for clientLog.

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
@ddaina I set you as reviewer so you can decide if it is worth to run again FunctionTests or not. I have already tested this in my branch, including simulating "cmsweb-test2 is down or S3 upload fails for some other reason" so am ready to merge.
We should rather decide, as per our chat on slack, if:
1. do we really want this
2. do we want to change/add info in s3report.json
3. do we eventually move this to prod still testing S3 uploads via cmsweb-test2 or do we move preprod to S3 and use that ?
but if answer to 1. is yes, we can address 2. and 3. after this is merged and tested.

**Comment by ddaina** [comment]
thanks @belforte, I am having a look.

**Comment by belforte** [comment]
few issues found during testing
- [ ] if cmsweb-test2 is down, client retries a few times causing crab submit to become slow and prints errors on the console which will confuse users
- [ ]  there are indications of sandbox naming confusion. Need to debug carefully

**Comment by belforte** [comment]
Thanks @ddaina for having fixed tests. I have solved the issues found this morning. The hex string one was indeed a true subtle bug, in the end all the "test uploads" were using the very same tarball name :-(
https://github.com/dmwm/CRABClient/pull/4997/commits/181e812e91818dbd84f57bb69e1c554a540437aa
Thanks for spotting it !!!!

**Comment by belforte** [comment]
please check again

**Comment by ddaina** [comment]
thanks @belforte,

Indeed now it is a bit difficult to track things when there is no logging about `s3` upload.
also, I stopped crabserver in `test2` to check how client behaves and error about service unavailability is still being reported:
```
[ddirmait@lxplus7122 crab_tasks]$ crab submit crabConfig_tutorial_MC_analysis_Prod.py
Will use CRAB configuration file crabConfig_tutorial_MC_analysis_Prod.py
Importing CMSSW configuration pset_tutorial_analysis.py
Finished importing CMSSW configuration pset_tutorial_analysis.py
Failed to get PreSignedURL from CRAB Server:
url=https://cmsweb-test2.cern.ch:8443/crabserver/dev/cache, code=503, reason=Service Unavailable, headers={'Date': 'Tue, 04 May 2021 14:41:37 GMT', 'Connectio
n': 'close', 'Content-Type': 'text/html', 'CMS-Server-Time': 'D=72255 t=1620139297900649', 'Server': 'Apache'}
Traceback (most recent call last):
  File "/afs/cern.ch/user/d/ddirmait/get_repos/CRABClient/src/python/CRABClient/JobType/UserTarball.py", line 48, in testS3upload
    tarballname=cachename, logger=logger)
  File "/afs/cern.ch/user/d/ddirmait/get_repos/CRABClient/src/python/ServerUtilities.py", line 685, in uploadToS3
    raise Exception('Failed to get PreSignedURL from CRAB Server:\n%s' % str(e))
Exception: Failed to get PreSignedURL from CRAB Server:
url=https://cmsweb-test2.cern.ch:8443/crabserver/dev/cache, code=503, reason=Service Unavailable, headers={'Date': 'Tue, 04 May 2021 14:41:37 GMT', 'Connection': 'close', 'Content-Type': 'text/html', 'CMS-Server-Time': 'D=72255 t=1620139297900649', 'Server': 'Apache'}
Failed to get PreSignedURL from CRAB Server:
url=https://cmsweb-test2.cern.ch:8443/crabserver/dev/cache, code=503, reason=Service Unavailable, headers={'Date': 'Tue, 04 May 2021 14:41:38 GMT', 'Connection': 'close', 'Content-Type': 'text/html', 'CMS-Server-Time': 'D=78412 t=1620139298453038', 'Server': 'Apache'}
Traceback (most recent call last):
  File "/afs/cern.ch/user/d/ddirmait/get_repos/CRABClient/src/python/CRABClient/JobType/UserTarball.py", line 48, in testS3upload
    tarballname=cachename, logger=logger)
  File "/afs/cern.ch/user/d/ddirmait/get_repos/CRABClient/src/python/ServerUtilities.py", line 685, in uploadToS3
    raise Exception('Failed to get PreSignedURL from CRAB Server:\n%s' % str(e))
Exception: Failed to get PreSignedURL from CRAB Server:
url=https://cmsweb-test2.cern.ch:8443/crabserver/dev/cache, code=503, reason=Service Unavailable, headers={'Date': 'Tue, 04 May 2021 14:41:38 GMT', 'Connection': 'close', 'Content-Type': 'text/html', 'CMS-Server-Time': 'D=78412 t=1620139298453038', 'Server': 'Apache'}
Sending the request to the server at cmsweb.cern.ch
Success: Your task has been delivered to the prod CRAB3 server.
Task name: 210504_144138:ddirmait_crab_20210504_164131
Project dir: crab_projects/crab_20210504_164131
Please use ' crab status -d crab_projects/crab_20210504_164131 ' to check how the submission process proceeds.
Log file is /afs/cern.ch/user/d/ddirmait/crab_tasks/crab_projects/crab_20210504_164131/crab.log
```

**Comment by ddaina** [comment]
also, coming back to your initial questions:

>     do we really want this

I would argue that it is a good approach to have realistic test of the planned changes and spot potential issues. So my answer is **yes**.

>     do we want to change/add info in s3report.json


assuming that current format is
```
{"status": "OK", "origin": "lxplus7118.cern.ch", "seconds": 0, "timestamp": "210503_134507.842", "ufcseconds": 0.06984496116638184, "KBytes": 16}
```
I would maybe think of adding username and taskname to ease automatic analysis of results. or is there a reason why it is not there?

   

>  do we eventually move this to prod still testing S3 uploads via cmsweb-test2 or do we move preprod to S3 and use that ?
but if answer to 1. is yes, we can address 2. and 3. after this is merged and tested.

If we are able to make errors/failures completely silent to users, I would say we move changes in this PR to prod. And then instead of testing s3 upload in preprod we focus on analyzing results in production.

**Comment by belforte** [comment]
> , I stopped crabserver in test2 to check how client behaves and error about service unavailability is still being reported:
I confirm the problem. Something is not adding up here. Investigating.

**Comment by belforte** [comment]
somehow when testing earlier I did not realize that I had made also a small, but critical, change in my local copy of the code but failed to replicate in git. Now I tried to also add some message to client log reporting that things went OK.

**Comment by belforte** [comment]
At last:
* cmsweb-test2 OFF
```
belforte@lxplus7100/Ora19> crab submit HC-splitByLumi.py
Will use CRAB configuration file HC-splitByLumi.py
Importing CMSSW configuration pset.py
Finished importing CMSSW configuration pset.py
Sending the request to the server at cmsweb.cern.ch
Success: Your task has been delivered to the prod CRAB3 server.
Task name: 210504_163349:belforte_crab_20210504_183343
Project dir: ./crab_20210504_183343
Please use ' crab status -d ./crab_20210504_183343 ' to check how the submission process proceeds.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/Ora19/crab_20210504_183343/crab.log
belforte@lxplus7100/Ora19> grep S3 crab_20210504_183343/crab.log 
DEBUG 2021-05-04 16:33:48.886 UTC: 	 Tarball upload to S3 failed:
DEBUG 2021-05-04 16:33:48.944 UTC: 	 Report of S3 upload stored on CrabCache as 210504_163348.793:s3report.json
DEBUG 2021-05-04 16:33:49.108 UTC: 	 Tarball upload to S3 failed:
DEBUG 2021-05-04 16:33:49.171 UTC: 	 Report of S3 upload stored on CrabCache as 210504_163349.018:s3report.json
belforte@lxplus7100/Ora19>
```
* cmsweb-test2 ON:
```
belforte@lxplus7100/Ora19> crab submit HC-splitByLumi.py
Will use CRAB configuration file HC-splitByLumi.py
Importing CMSSW configuration pset.py
Finished importing CMSSW configuration pset.py
Sending the request to the server at cmsweb.cern.ch
Success: Your task has been delivered to the prod CRAB3 server.
Task name: 210504_163438:belforte_crab_20210504_183431
Project dir: ./crab_20210504_183431
Please use ' crab status -d ./crab_20210504_183431 ' to check how the submission process proceeds.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/Ora19/crab_20210504_183431/crab.log
belforte@lxplus7100/Ora19> grep S3 crab_20210504_183431/crab.log 
DEBUG 2021-05-04 16:34:37.309 UTC: 	 Successfully uploaded tarball to S3 as well
DEBUG 2021-05-04 16:34:37.376 UTC: 	 Report of S3 upload stored on CrabCache as 210504_163435.955:s3report.json
DEBUG 2021-05-04 16:34:38.650 UTC: 	 Successfully uploaded tarball to S3 as well
DEBUG 2021-05-04 16:34:38.712 UTC: 	 Report of S3 upload stored on CrabCache as 210504_163437.458:s3report.json
belforte@lxplus7100/Ora19> 

```

**Pull request merged**
