### PR TITLE
Improve automatic splitting et al.

### PR DESCRIPTION
**Pull request by matz-e**
Companion to dmwm/CRABServer#5627:

* Change units for automatic splitting to minutes rather than seconds
* Make automatic splitting default splitting algorithm
* Accept fractional `Data.totalUnits`
* Improve automatic splitting status:
  * Don't display splitting and failed jobs by default in summary
  * Only split job display into probes, processing, tails with `--long`
  * Mark failed processing jobs as `rescheduled`
  * Probe jobs are `no output` rather than `failed`/`finished`
  * Don't allow to resubmit processing jobs with automatic splitting

### CODE REVIEW

**Comment by lecriste** [comment]
All my tests with the latest client and TW versions (respectively 3.3.1802.rc3 and 3.3.18.02.rc1) were successfully.
I noticed just some minor issues (not sure this is the right PR to comment on):

- No main jobs log available in the [dashboard](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=lecriste&refresh=0&table=Jobs&p=1&records=25&sorting%5B%5D=5&sorting%5B%5D=desc&activemenu=2&status=&site=&tid=180204_235534%3Alecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod_3-3-18-02-rc3fromSubm)

- `crab getoutput` returns this message for any job id:
No files to retrieve.

- `crab getlog` fails with this message:
> Warning: Failed retrieving cmsRun_1-12.log.tar.gz
> 	  2 [se][ls][srm_invalid_path] no such file or directory /pnfs/iihe/cms/store/user/lecriste/cata/singlemuon/crab3_tutorial_automaticsplitting_analysis/180204_235534/0000/log/cmsrun_1-12.log.tar.gz

- If I ask `crab getlog` for a jobid out of range I get:
> The job with id 1-31 is not in a valid state to retrieve output files
instead of the usual message.

**Comment by matz-e** [comment]
You used too much disk again, not sure if the logs will be saved in that case.

I'll have a look at the other items.

**Comment by matz-e** [comment]
What's the right client to test in `/cvmfs`?

**Comment by belforte** [comment]
job terminated by wrapper (50662) i.e. bya condor_rm does usually result indeed in no logs and no log in dashboard is the same as no log from getlog since both try a wget from the same location. So this is not related to automatic splitting. It is a different story that some time ago HTCondor was modified to return logs even in that case, and at times this works, but mostly not. I never had the time to follow up.

So I'd be only worried about the getoutput.

**Comment by matz-e** [comment]
Yes, just submitted a task to preprod. I haven't submitted to my own VM since I disable all transfers there.

**Comment by lecriste** [comment]
> You used too much disk again, not sure if the logs will be saved in that case.

I did it on purpose to get some failed jobs to play with. 


> What's the right client to test in `/cvmfs`?

It's 3.3.1802.rc3
```
export CRAB_SOURCE_SCRIPT="/cvmfs/cms.cern.ch/crab3/crab_pre_standalone.sh"
source /cvmfs/cms.cern.ch/crab3/crab_pre.sh

```
> It is a different story that some time ago HTCondor was modified to return logs even in that case, and at times this works, but mostly not.

Indeed I remember I saw the main jobs log even in such case in the past.

**Comment by matz-e** [comment]
>>   You used too much disk again, not sure if the logs will be saved in that case.

> I did it on purpose to get some failed jobs to play with.

I have this module to fail certain jobs: https://github.com/matz-e/crab-fail-job

**Comment by matz-e** [comment]
@lecriste I can't reproduce your issues with `getlog` and `getoutput`. Note that I source `/cvmfs/cms.cern.ch/crab3/crab_pre_standalone.sh` directly. My output for a recent task with the latter client:
```
❯ TauRoast master matze@lxplus041 [16s] crab getoutput --jobids 1-19
Warning: Incompatible CRABClient version 3.3.1802.rc4
Server is saying that compatible versions are: [u'3.3.4.rc3', u'development', u'development']
Warning: Incompatible CRABClient version 3.3.1802.rc4
Server is saying that compatible versions are: [u'3.3.4.rc3', u'development', u'development']
Setting the destination to /afs/cern.ch/work/m/matze/ttH/CMSSW_8_0_26_patch1/src/ttH/TauRoast/crab_0114_automatic_get_stuff_01/results
Retrieving 1 files
Warning: Incompatible CRABClient version 3.3.1802.rc4
Server is saying that compatible versions are: [u'3.3.4.rc3', u'development', u'development']
Will use `gfal-copy` command for file transfers
Placing file 'ttl_test_1-19.root' in retrieval queue
Please wait
Retrieving ttl_test_1-19.root
Success: Success in retrieving ttl_test_1-19.root
Success: All files successfully retrieved
Log file is /afs/cern.ch/work/m/matze/ttH/CMSSW_8_0_26_patch1/src/ttH/TauRoast/crab_0114_automatic_get_stuff_01/crab.log

❯ TauRoast master matze@lxplus041 [1m 50s] crab getlog --jobids 146,1-19
Warning: Incompatible CRABClient version 3.3.1802.rc4
Server is saying that compatible versions are: [u'3.3.4.rc3', u'development', u'development']
Warning: Incompatible CRABClient version 3.3.1802.rc4
Server is saying that compatible versions are: [u'3.3.4.rc3', u'development', u'development']
Setting the destination to /afs/cern.ch/work/m/matze/ttH/CMSSW_8_0_26_patch1/src/ttH/TauRoast/crab_0114_automatic_get_stuff_01/results
Retrieving 2 files
Warning: Incompatible CRABClient version 3.3.1802.rc4
Server is saying that compatible versions are: [u'3.3.4.rc3', u'development', u'development']
Will use `gfal-copy` command for file transfers
Placing file 'cmsRun_1-19.log.tar.gz' in retrieval queue
Retrieving cmsRun_1-19.log.tar.gz
Placing file 'cmsRun_146.log.tar.gz' in retrieval queue
Please wait
Retrieving cmsRun_146.log.tar.gz
Success: Success in retrieving cmsRun_1-19.log.tar.gz
Success: Success in retrieving cmsRun_146.log.tar.gz
Success: All files successfully retrieved
Log file is /afs/cern.ch/work/m/matze/ttH/CMSSW_8_0_26_patch1/src/ttH/TauRoast/crab_0114_automatic_get_stuff_01/crab.log
```

**Comment by lecriste** [comment]
Then probably [it](https://github.com/dmwm/CRABClient/pull/4738#issuecomment-363050598) is due to the previous client version I was using (rc3).

With a new [task](https://cmsweb.cern.ch/crabserver/ui/task/180207_143738%3Alecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc4_testDefaultSplitting) in which I did not set the `config.Data.splitting` parameter (in order to test its default value) I get:
```
[lecriste@lxplus029 test]$ crab getoutput --jobids 1
ERROR: AttributeError: 'ConfigSection' object has no attribute 'splitting'

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: 3.3.1802.rc4
	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/l/lecriste/CatA/AutomaticSplitting/CMSSW_9_3_0_pre1/test/crab_projects/crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc4_testDefaultSplitting/crab.log to the CRAB cache.
```
Log file URL: https://cmsweb-testbed.cern.ch/crabcache/logfile?name=180207_143738:lecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc4_testDefaultSplitting.log&username=lecriste

**Comment by matz-e** [comment]
Could you please test if #4746 fixes this? It looks like an omission from when I made the original PR to set automatic as the default — since my dev machine has troubles with stageout, I often test without transferring anything.

**Comment by belforte** [comment]
@matz-e I am a bit confused here, sorry. I thought last test from @lecriste indicated that automatic as default id in the server, but still no accepted by client (no big deal). So how can a config. w/o a splitting type defined be the problem ?
IIUC all that latest commit does is to enforce a default for splitting type.

**Comment by matz-e** [comment]
@belforte the client takes care of enforcing/setting the default. Due to the way the defaults are set, there are a few places where a default splitting has to be explicitly checked/specified. The client submits with a default of automatic splitting, but then the get* commands break…

The status and get* commands use a joblist that has to be parsed differently for automatic splitting (dashes in the list are a single jobid) and other modes (dashes in the list specify a range). To get the right way of parsing the list, it relies on the cached configuration, where the defaults of the `ClientMapping` are not applied.

**Comment by lecriste** [comment]
I confirm #4746 fixed [this](https://github.com/dmwm/CRABClient/pull/4738#issuecomment-363828095) but I still see the [previos behaviour](https://github.com/dmwm/CRABClient/pull/4738#issuecomment-363050598) with this [task](https://cmsweb.cern.ch/crabserver/ui/task/180207_143738%3Alecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc4_testDefaultSplitting) also for tail jobs. Maybe it is due to jobs being in transferring status because of the preprod instance?

**Comment by matz-e** [comment]
Yes, I don't think that you can get the output/logs while they are still being transferred to the final SE. I've found preprod to be unreliable w.r.t. ASO, I've switched to using my own dev instance with direct stageout/no ASO…

**Comment by matz-e** [comment]
As for the output of crab when asking for an invalid jobid, what message do you expect? I get the same message for all splitting modes… [this is also the only error message in the code](https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/getcommand.py#L172).

I would suggest to move any discussion of open items to separate issues, too. Digging this out after I've read the notifications on my phone's browser is getting tedious :)

**Comment by belforte** [comment]
+1
especiallya closed pull request is not a place for a discussion thread nor to report new problems.
Which is another reason why it is good to have an issue (which if needed can be reopened) before making a PR, unless the PR is kind of trivial

**Pull request merged**
