### PR TITLE
Update bash completion script

### PR DESCRIPTION
**Pull request by matz-e**
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2781.html

I just ran `scripts/generate_completion.py`…

### CODE REVIEW

**Comment by matz-e** [comment]
Uhm… @ericvaandering that bot behavior does not seem right to me…

**Comment by ericvaandering** [comment]
Yeah, the CRAB bot has been useless for a while now. On my list of things to re-vamp

**Comment by emaszs** [comment]
Thank you @matz-e. @belforte, @mmascher, should I merge this and deploy a patch release for the production client? I can trust that this should work but I'm not too familiar, also I won't be around next week. Since I haven't started switching the client commands yet the autocompletion will need to be generated again during validation.

**Comment by belforte** [comment]
do we still have a pre-prod client ? If so, can you update that, but leave production as is ?
Then worry about production client once you are back.

**Comment by emaszs** [comment]
Yes of course, I'll apply this to pre-prod then.

**Pull request merged**
