### PR TITLE
Optimize getDoubleLumis function speed

### PR DESCRIPTION
**Pull request by blinkseb**
Hi,

I found this issue when investigating why `crab report` takes ages when ran over a big task (> 100 jobs). In my case, running `crab report` on `DY M-50` took approximately 30 minutes ... Looking at the crab log, I've seen that something fishy occurs between the server response and the first log output:

```
DEBUG 2015-12-02 15:55:34,663:   Result: <...>
INFO 2015-12-02 16:28:23,413:    683 files have been processed
```

I've been able to pinpoint the issue to the function `getDoubleLumis`, which find the duplicated lumi sections. I've changed a bit the code of the function, which lead to a huge gain in runtime. In my test-case, I have only one run (it's MC), and 299900 lumi-sections. Runtimes are:

 - Original code: > 20 mins (I stop the execution)
 - New code: ~ 500ms

It'd be great if this can be merged and available in the next crab3 release!

Thanks,

### CODE REVIEW

**Comment by AndresTanasijczuk** [comment]
This PR looks ok to me. I tested it and it is true what @blinkseb says about the runtimes.

**Comment by ericvaandering** [comment]
test this please

**Comment by blinkseb** [comment]
Is there something I have to fix in my patch?

**Comment by AndresTanasijczuk** [comment]
No, you don't have to fix anything.

**Comment by mmascher** [comment]
Thanks a lot @blinkseb , for sure this will be included in the next CRAB3 release (beginning of February)! Please, do not hesitate if you have other questions/suggestions :)

**Pull request merged**
