### PR TITLE
Fixed getlog --short to validate jobids. Fix #4803

### LINKED ISSUE #4803: getlog --short fails with ERROR: ValueError: need more than 1 value to unpack
crab client log:
```
DEBUG 2019-03-19 17:03:36,287: 	 Options use: ['--short', '--jobid=1', '-d', 'crab_20190319_103049/']
INFO 2019-03-19 17:03:36,401: 	 Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: [u'3.3.1704', u'3.3.1705', u'3.3.1706', u'3.3.1707', u'3.3.1711', u'3.3.1802', u'3.3.1803', u'3.3.1804', u'3.3.1804.patch1', u'3.3.1805', u'3.3.1805.patch1', u'3.3.1809', u'3.3.1812', u'3.3.1902.patch1', u'3.3.1903.patch1', u'3.3.1902.rc1']
DEBUG 2019-03-19 17:03:36,401: 	 Instance is prod
DEBUG 2019-03-19 17:03:36,401: 	 Server base url is cmsweb.cern.ch
DEBUG 2019-03-19 17:03:36,401: 	 Command url /crabserver/prod/workflow
INFO 2019-03-19 17:03:36,485: 	 Setting the destination to /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/mio/crab_20190319_103049/results 
INFO 2019-03-19 17:03:36,485: 	 Retrieving...
ERROR 2019-03-19 17:03:36,490: 	 Unhandled Exception!
ERROR 2019-03-19 17:03:36,490: 	 need more than 1 value to unpack
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 160, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 148, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 42, in __call__
    failed, success = self.retrieveShortLogs(webdir, self.proxyfilename)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 98, in retrieveShortLogs
    for _, jobid in self.options.jobids:
ValueError: need more than 1 value to unpack
ERROR 2019-03-19 17:03:36,558: 	 ERROR: ValueError: need more than 1 value to unpack

```

Looking at the code it seems broken since ~ever  in
https://github.com/dmwm/CRABClient/blob/6a03ba37b3c22644ff9d82a09448a2faf0dab86f/src/python/CRABClient/Commands/getlog.py#L98
since `options.jobids` is a simple list with a single value for each item.

I have no idea if earlier jobids was a different structure, already previous version of getlog indicates a two value list for each jobid item:
https://github.com/dmwm/CRABClient/commit/3bbc51c7448dc077b4b8cd26c0191114d79dc8de

Maybe it has broken forever ?

### PR DESCRIPTION
**Pull request by cbbrainerd**
crab getlog --short does not function because the jobids are not validated. Fixes #4803.

### CODE REVIEW

**Comment by belforte** [comment]
thanks @cbbrainerd  looks like this will do. We'll give it a try.

**Comment by belforte** [comment]
@lecriste up to you if you prefer to merge first and test, or test first. Merging first is likley less work.

**Comment by lecriste** [comment]
@cbbrainerd [this line](https://github.com/dmwm/CRABClient/pull/4816/files#diff-ab72a7e543804ee99fa136076bd00f32R29) would suffer from [this issue](https://github.com/dmwm/CRABClient/issues/4757).
Since the [same code](https://github.com/dmwm/CRABClient/commit/7b41c2d26864537360c3524492d89b4f17ca7891#diff-1259e30c4a45cc5db4edceac9c55d399R76) is already in the `getcommand` subclass, I think we better enclose it in a subclass method and call it here.

**Comment by cbbrainerd** [comment]
I updated it to try fetching the splitting from the .requestcache and to request it from the DB if that fails. It didn't seem to make sense to enclose it in a subclass method since as far as I can tell the getcommand always has to fetch information from the DB anyway but getlog --short does not.

**Comment by belforte** [comment]
@cbbrainerd I do not see where `validateJobids` is imported from. So can't understand why you and @lecriste worry about the splitting algorithm, which IIUC is what caused this discussion about caching etc.
Nor I can see how it can run, was this tested ? Maybe I am missing something.

There is a `validateJobids` in CRABClient already but does not have a `splitting` argument:
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/ClientUtilities.py#L705-L722

**Comment by cbbrainerd** [comment]
@belforte `validateJobids` is indeed imported from ClientUtilities. There is no `splitting` argument, but an `allowLists` argument. The problem here is that automatic splitting gives job ids like "1-500" for tail jobs. So `--jobids` cannot take lists in that case, since "1-500" is ambiguous between "a list of jobids from 1 to 500" and "a tail job with an jobid of 1-500." So the `validateJobids` is called with the argument `(allowLists=(splitting!="automatic))` so that lists are forbidden with automatic splitting and allowed otherwise.

**Comment by belforte** [comment]
thanks @cbbrainerd . Sorry for not having read correctly Can you please add the missing import ?

**Comment by cbbrainerd** [comment]
@belforte The import is added, in the commit pushed 20 hours ago.

**Comment by belforte** [comment]
Thansk. I tested this works finely on a simple task.
OTOH when I re-created the work directory with `crab remake --task` I got this error [1]

[1]
```
DEBUG 2019-08-30 16:34:10,323: 	 Instance is preprod
DEBUG 2019-08-30 16:34:10,323: 	 Server base url is cmsweb-testbed.cern.ch
DEBUG 2019-08-30 16:34:10,323: 	 Command url /crabserver/preprod/workflow
ERROR 2019-08-30 16:34:10,412: 	 Unhandled Exception!
ERROR 2019-08-30 16:34:10,412: 	 'desc'
Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 161, in <module>
    client()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab", line 148, in __call__
    self.cmd()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/Commands/getlog.py", line 48, in __call__
    splitting=getColumn(dictresult,'tm_split_algo')
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python/CRABClient/ClientUtilities.py", line 179, in getColumn
    columnIndex = dictresult['desc']['columns'].index(columnName)
KeyError: 'desc'
ERROR 2019-08-30 16:34:10,413: 	 ERROR: KeyError: 'desc'
ERROR 2019-08-30 16:34:10,413: 	 
```

**Comment by belforte** [comment]
In case one asks, the error is the same for a task in production instance instead of pre-prod
```
belforte@lxplus601/belforte> crab remake --task 190826_171346:belforte_crab_20190826_191342
Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: [u'3.3.1704', u'3.3.1705', u'3.3.1706', u'3.3.1707', u'3.3.1711', u'3.3.1802', u'3.3.1803', u'3.3.1804', u'3.3.1804.patch1', u'3.3.1805', u'3.3.1805.patch1', u'3.3.1809', u'3.3.1812', u'3.3.1902.patch1', u'3.3.1903.patch1', u'3.3.1904', u'3.3.1905.rc1']
Remaking crab_20190826_191342 folder.
Remaking .requestcache file.
Success: Finished remaking project directory crab_20190826_191342
Log file is /tmp/belforte/crab.log
belforte@lxplus601/belforte> crab status -d crab_20190826_191342/
Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: [u'3.3.1704', u'3.3.1705', u'3.3.1706', u'3.3.1707', u'3.3.1711', u'3.3.1802', u'3.3.1803', u'3.3.1804', u'3.3.1804.patch1', u'3.3.1805', u'3.3.1805.patch1', u'3.3.1809', u'3.3.1812', u'3.3.1902.patch1', u'3.3.1903.patch1', u'3.3.1904', u'3.3.1905.rc1']
CRAB project directory:		/tmp/belforte/crab_20190826_191342
Task name:			190826_171346:belforte_crab_20190826_191342
Grid scheduler - Task Worker:	crab3@vocms069.cern.ch - crab-prod-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/190826_171346%3Abelforte_crab_20190826_191342
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=belforte&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=190826_171346%3Abelforte_crab_20190826_191342
New dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=190826_171346%3Abelforte_crab_20190826_191342
In case of issues with the new dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
Status on the scheduler:	COMPLETED

Jobs status:                    finished     		100.0% (5/5)

No publication information (publication has been disabled in the CRAB configuration file)

Warning: the max jobs runtime is less than 30% of the task requested value (21 min), please consider to request a lower value for failed jobs (allowed through crab resubmit) and/or improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task.

Warning: the average jobs CPU efficiency is less than 50%, please consider to improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task

Summary of run jobs:
 * Memory: 2MB min, 17MB max, 6MB ave
 * Runtime: 0:03:38 min, 0:04:59 max, 0:04:00 ave
 * CPU eff: 3% min, 27% max, 15% ave
 * Waste: 0:07:48 (28% of total)

Log file is /tmp/belforte/crab_20190826_191342/crab.log
belforte@lxplus601/belforte> crab getlog --short --jobids 2,3 -d crab_20190826_191342/
Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: [u'3.3.1704', u'3.3.1705', u'3.3.1706', u'3.3.1707', u'3.3.1711', u'3.3.1802', u'3.3.1803', u'3.3.1804', u'3.3.1804.patch1', u'3.3.1805', u'3.3.1805.patch1', u'3.3.1809', u'3.3.1812', u'3.3.1902.patch1', u'3.3.1903.patch1', u'3.3.1904', u'3.3.1905.rc1']
ERROR: KeyError: 'desc'

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: development
	The log file /tmp/belforte/crab_20190826_191342/crab.log has been uploaded automatically to the CRAB cache.
	Please email the following URL 'https://cmsweb.cern.ch/crabcache/logfile?name=2019-08-30_164030_crab.log&username=belforte' to hn-cms-computing-tools@cern.ch if you need help from Analysis Operations.
belforte@lxplus601/belforte> 

```

**Comment by belforte** [comment]
@lecrtiste I hope I understand correctly your comments as pointing to a possible issue after `crab --remake` but I can't really figure out which lines you refer to from the links which you pasted, they point (at least for me) to the full list of differences in the commit.

**Comment by belforte** [comment]
while if I issue same command on the original work directory, it is OK
```
belforte@lxplus601/TC3> pwd
/afs/cern.ch/user/b/belforte/WORK/CRAB3/TC3
belforte@lxplus601/TC3> crab getlog --short --jobid 3,4 -d crab_20190826_191342/
Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: [u'3.3.1704', u'3.3.1705', u'3.3.1706', u'3.3.1707', u'3.3.1711', u'3.3.1802', u'3.3.1803', u'3.3.1804', u'3.3.1804.patch1', u'3.3.1805', u'3.3.1805.patch1', u'3.3.1809', u'3.3.1812', u'3.3.1902.patch1', u'3.3.1903.patch1', u'3.3.1904', u'3.3.1905.rc1']
Server result: http://vocms069.cern.ch/mon/cms1627/190826_171346:belforte_crab_20190826_191342
Setting the destination to /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20190826_191342/results 
Retrieving...
Retrieved job_out.3.0.txt
Retrieved job_out.4.0.txt
Success: All files successfully retrieved.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20190826_191342/crab.log
belforte@lxplus601/TC3> 
```
of course going from 'getlog --short is fully broken' to 'it is broken after a crab --remake` still is improvement, so if @lecriste agrees I propose to merge this PR and open a new issue

**Comment by belforte** [comment]
seems to me that a bunch of the new code could be replaced with:
```
crabDBInfo, _, _ =  server.get(uri, data = {'subresource': 'search', 'workflow': taskname}
splitting = getColumn(crabDBInfo, 'tm_split_algo')
```
It may not be worth to make a new class for these two lines.

Maybe we should pull crabDBInfo in SubCommand so that it is available to all commands ?
AFAICT it is currently used in getcommand , resubmit, purge, status, preparelocal. Once we add getlog, only kill is left of the most used commands.

**Comment by lecriste** [comment]
@cbbrainerd why did you change the code related to `webdir`?

**Comment by lecriste** [comment]
I think this is the solution with minimal change:
https://github.com/lecriste/CRABClient/commit/3e4b682420f90de41134429b28ecfd39fabc987a

Did not test it yet.

**Comment by cbbrainerd** [comment]
> @cbbrainerd why did you change the code related to `webdir`?

It seems to me that getProxiedWebDir is redundant if we already have `dictresult, status, _ =  server.get(uri, data = inputlist)`. Looking at the [code](https://github.com/lecriste/CRABServer/blob/e26dcf0bf6cce4dc9141e51b21d25e9daf43b2fe/src/python/ServerUtilities.py#L159) for `webdir`, it seems that we should be able to fetch the splitting and the webdir in one to the server.

**Comment by belforte** [comment]
@cbbrainerd thanks for your pointing to the solution here, I believe that @lecriste or myself can finalize trying to keep some consistency with rest of CRAB code. It is indeed a bit annyoing that there is an API call which returns all DB info about a task, like splitting algorithm and webdir, but not proxiedwebdir. The whole  thing about proxied webdir could benefit from a big strike, since the original use case (CRAB servers at UCSD) is no longer valid.
@lecriste your latest fix does not work as coded but it surely can be made to work. But it is really time to converge here. Let me know if you do it (including testing after crab --remake) or if I do.

**Comment by lecriste** [comment]
I can make it work and test by tomorrow.

**Comment by lecriste** [comment]
@cbbrainerd feel free to test the new code once, in a couple of hours, 
`ll /cvmfs/cms.cern.ch/crab3/crab.sh`
will point to the latest **3.3.1909** tag:
`lrwxrwxrwx. 1 cvmfs cvmfs 84 Apr 18 20:58 /cvmfs/cms.cern.ch/crab3/crab.sh -> /cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/etc/init-light.sh`

**Comment by lecriste** [comment]
Done in https://github.com/dmwm/CRABServer/pull/5944

**Pull request closed without merging**
