### PR TITLE
Make JobType.psetName not mandatory for scriptExe.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
This is the client part for https://github.com/dmwm/CRABServer/issues/4922

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by belforte** [comment]
@mmascher I can't easily figure out the status of this. IIUC it can't be cleanly merged so would need quite some work to include it. Can you tell if there's useful code to rescue or it was simply an attempt to improve messaging in some corner case. We do not have any obvious need to address in the scriptExe area, it is possible that the original problem was already solved by some other change.
I am very strongly inclined to close.

**Comment by belforte** [comment]
so many years since it was proposed, no burning need for it, can't be cleanly merged and tested... let's close, if needs arise it would easier to do from scratch in current code.

**Pull request closed without merging**
