### PR TITLE
Seperate out COMP and CMSSW envs

### PR DESCRIPTION
**Pull request by PerilousApricot**
Not quite ready, I need the 2nd commit:

1) Add a layer of indirection to the "target" CRAB script to allow us to
inject environment manipulation between the user and CRAB

2) Hook SCRAMEnvironment and CMSSWConfiguration to execute in a subprocess using the target CMSSW environment

### CODE REVIEW

**Comment by mmascher** [comment]
Hi Andrew, I am working on the very same thing and I was planning to include it in the June release. Let me share my code and start from that before we worn on the same thing..

**Comment by mmascher** [comment]
There you go https://github.com/dmwm/CRABClient/pull/4483

**Comment by ericvaandering** [comment]
test this please

**Comment by belforte** [comment]
should not be needed anymore once we deploy the lightweigth client which lives withing CMSSW.
@PerilousApricot can we close w/o merging ?

**Comment by mmascher** [comment]
Closing without merging since we have the crab_light on cvmfs now

**Pull request closed without merging**
